# Generated by Django 3.1 on 2020-08-08 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultor', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Aberto'), ('E', 'Andamento'), ('F', 'Fechado')], max_length=1, null=True, verbose_name='Status')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preço')),
                ('pagamento', models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('CD', 'Cartão Debito'), ('CC', 'Cartão Credito')], max_length=2, null=True, verbose_name='Pagamento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.pessoa')),
                ('consultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultor.consultor')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultor.servico')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
    ]
