# Generated by Django 3.1 on 2020-08-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Consultor')),
                ('telefone', models.CharField(blank=True, max_length=9, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Consultor',
                'verbose_name_plural': 'Consultores',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Seviço')),
                ('pagamento', models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('CD', 'Cartão Debito'), ('CC', 'Cartão Credito')], max_length=2, verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
