# Generated by Django 3.1 on 2020-08-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='valor_servico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valor Servico'),
        ),
    ]
